### PR TITLE
Samples - housekeeping

### PR DESCRIPTION
**Pull request by rmoff**
- Tidy up samples, update README
- Fix paths that changed

### CODE REVIEW

**Comment by kesarwam** [comment]
image
Link "additional Airflow samples here" goes to wrong URL "https://github.com/treeverse/lakeFS-samples/tree/main/03-multiple-samples"

**Comment by kesarwam** [comment]
Can we move Airflow demo higher up in 00_index.ipynb because Airflow demos are very popular?

**Comment by kesarwam** [comment]
image

You can delete many hidden folders e.g. .cache, .ipynb_checkpoints etc.

**Comment by kesarwam** [comment]
image

Do we have "ML Experimentation 01" also?

**Comment by kesarwam** [comment]
It might be good to have both delta lake notebooks together:

image

**Comment by kesarwam** [comment]
I get this error if I try to start lakefs-samples container:

image

**Comment by kesarwam** [comment]
Can you fix the README.md for airflow-01 inside 01_standalone_examples? It has listing of all previous notebooks under 03-multiple-samples and command "cd lakeFS-samples/03-multiple-samples" will not work now.

**Comment by rmoff** [comment]
> image Link "additional Airflow samples here" goes to wrong URL "https://github.com/treeverse/lakeFS-samples/tree/main/03-multiple-samples"

Thanks, fixed

> Can we move Airflow demo higher up in 00_index.ipynb because Airflow demos are very popular?

I've added a note at the top to draw attention to them


> image
> 
> You can delete many hidden folders e.g. .cache, .ipynb_checkpoints etc.

These are local to your machine, they're not in GitHub 
CleanShot_2023-06-14_at_08 58 40@2x



> image
> 
> Do we have "ML Experimentation 01" also?

Yes, under Standalone Demos


> It might be good to have both delta lake notebooks together:
> 
> image

Done

> Can you fix the README.md for airflow-01 inside 01_standalone_examples? It has listing of all previous notebooks under 03-multiple-samples and command "cd lakeFS-samples/03-multiple-samples" will not work now.

Done


> I get this error if I try to start lakefs-samples container by using Docker Desktop:
> 
> image

I don't think that's related to this PR. Can you open another issue with details of how to reproduce, what version of Docker Desktop you're running, OS, etc.

**Comment by kesarwam** [comment]
@rmoff Can you please change back standalone Dagster integration from Docker Compose to Docker Run? Otherwise it doesn't work if lakefs-samples container is already there. You can test it.

**Pull request merged**
