### PR TITLE
Fix: lakeFS instrumentation

### PR DESCRIPTION
**Pull request by N-o-Z**
docker file used wrong environment variable for credentials causing lakeFS samples repo instrumentation to be registered as "Run"

### CODE REVIEW

**Review by nopcoder — CHANGES_REQUESTED** [review]
How is the name of env variable fix this issue? The env that was used was configured to to enable running lakectl commands that will work with the same lakefs instance.
So I guess I am missing the main issue.

**Comment by N-o-Z** [comment]
> How is the name of env variable fix this issue? The env that was used was configured to to enable running lakectl commands that will work with the same lakefs instance. So I guess I am missing the main issue.

We rely on an environment variable:

```
func getInstrumentationMetadata() string {
	lakefsAccessKeyID := viper.GetString("installation.access_key_id")
	switch {
	case strings.HasSuffix(lakefsAccessKeyID, "LKFSSAMPLES"):
		return InstrumentationSamplesRepo
	case strings.HasSuffix(lakefsAccessKeyID, "QUICKSTART"):
		return InstrumentationQuickstart
	default:
		return InstrumentationRun
	}
}
```

**Comment by N-o-Z** [comment]
Notebook is broken on main - unrelated to changes

**Review by nopcoder — CHANGES_REQUESTED** [review]
Thanks @N-o-Z - I undestand the change now, but I see that the docker compose running lakefs setup while using the `installation` feature.
Think we just need to define the username name and drop the setup code from there.

**Review by nopcoder — APPROVED** [review]
LGTM!

**Pull request merged**
