### PR TITLE
Restructure/Update lakeFS-samples to use central docker-compose file where possible

### PR DESCRIPTION
**Pull request by rmoff**
For background to this change please see https://github.com/treeverse/lakeFS/issues/5739 and https://github.com/treeverse/devex-internal/issues/262

This PR implements the bulk of the easy migrations. Remaining work is listed here https://github.com/treeverse/lakeFS/issues/5739#issuecomment-1574049069

- Updated Everything Bagel Docker Compose
- Add some sample data and notebooks
- Moved 05-dev/test to new combined location
- Add minio and jupyter login details to boot screen
- Update jupyter image - add tabulate and disable news prompt
- Migrated Spark Demo notebook
- Migrated Spark Demo notebook
- Tweaks to dev/test notebook
- Rework notebooks to use common header
- Fix the lakeFS connection in airflow
- fix name
- Update Airflow example for new structure
- Tweaks
- Update versions, add import example notebook
- Update README
- s/storageRootPath/storageNamespace
- Remove redundant folder, rename other
- Moved DAIS notebook to central examples
- Tidy up WAP
- Move sample data / add WAP notebook / update README to add env URLs
- Add Spark port
- Migrate and update Delta Lake demo
- tweak repo name
- Update index
- Migrate reprocess/backfill notebook
- Show notebooks in root of Jupyter
- Migrate 08 data lineage notebook
- Migrate delta-diff notebook
- Move logo to local storage
- Data files for delta diff notebook
- Migrate ML experimentation notebook
- Migrate Version Control of multi-buckets pipelines notebook
- renamed migrate/repo folder (not migrated)
- Change index to use UL instead of table
- Update index, move ML experimentation (dogs) into demos area, etc
- Tidyup and fix my dodgy git work
- Clarify instructions
- Update instructions
- Add labelbox to index
- Move labelbox demo to standalone folder
- Move oreilly ci/cd challenge and synapse notebook
- Move WAP to notebooks folder, update for nessie
- Move dagster demo to standalone folder, add docker-compose
- Tweak readme

### CODE REVIEW

**Comment by rmoff** [comment]
@iddoavn thanks for spending so much time on this, and for all the great feedback! 
 
> 1. About the readme - I would suggest the default will be starting up without the lakeFS server. Is there a way to have the simple command do that?

✅ Yes, that's the default in the README as it stands

CleanShot_2023-06-06_at_10 27 34

> 2. The wording can be better IMO.
>    First, no question about starting without a lakeFS Server (let's just assume they went through the quickstart and have a lakeFS server, or went through cloud).

That's a *huge* assumption to make though, and I'm not sure for what benefit. 

- If they already have one, then great, they parse and move on. 
- If they *don't* have one then giving them this first step without the context of needing lakeFS is a really sharp edge - they'll spin something up that won't work. 

An important point here is that even if they have been through quickstart, the quickstart docker container can't just be run with the Jupyter notebook - they need to be wired together, which is what the Docker Compose does.

> 3. Since we want this to be as useful for folks running with with and without lakeFS, I think we should not pre-populate the keys and lakeFS server address.

I disagree - if we don't pre-populate it then *everyone* has to amend the notebook to run it. If we do pre-populate it then only those bringing their own lakeFS instances will need to. 

Put another way, I guess I don't understand why we wouldn't pre-populate it if it will help a proportion of our users? 

> 4. Don't know if this is an issue or not. However - In test-dev this command took around 5 minutes for me:
>    `movies_df.write.option("header",True)\`
>    `.partitionBy("country")\`
>    `.mode("append")\`
>    ` .parquet(f"{staging_long_path}/analytics/movies-by-country-parquet")`

I've not changed the content that was there, so this won't be related to this PR. 

> 5. We should remove all the output from the previous run before we upload the notebooks.

✅ I agree - done.

> 6. In the 00_index, I suggest having first spark_demo since it is the most commonly used one.

✅ I agree - done.

> 7. On delta-diff.ipynb I think we want to change the last printout to build the repo (in case you are not running on everything bagel):
>    `print(f"Go to lakeFS UI and click on 'Show table changes':\n {lakefsEndPoint}/repositories/{repo.id}/compare?ref=main&compare=modify_user_data&prefix=demo%2F")`

✅ Nice! I like it. I'll add it. I've added some logic to handle local endpoints (`lakefs` won't be resolvable from the user's host machine)

> 8. For multi bucket import example -
>    (A) this is the older example, that still includes `status_resp_import_branch` and then merge. This will not work on the latest import, can you bring the new one instead?

✅ Fixed

>    (B) this use case typically comes in a MLOps environment with unstructured data. I think we should keep it with the images by default if that is possible.

✅ Sure thing - added

> 9. On ML Experimentation the configure boto3 client should be:
>    `s3_client = boto3.client('s3',`
>    `    endpoint_url=lakefsEndPoint,`
>    `    aws_access_key_id=lakefsAccessKey,`
>    `    aws_secret_access_key=lakefsSecretKey)`
> 
> `s3_resource = boto3.resource('s3',` ` endpoint_url=lakefsEndPoint,` ` aws_access_key_id=lakefsAccessKey,` ` aws_secret_access_key=lakefsSecretKey)` Otherwise, you will get an error when trying to read later on.

✅ Good catch, thanks. Fixed.

> 10. In 00_index. I will call the items in the list :
>     schema validation - prevent schema changes and not hooks, since that is what someone will be looking for.
>     Quality validation - allow only specific file formats (or some better naming). Etc.

✅ done

> 11. The RBAC image is missing so the reference doesn’t work.

✅ fixed

> 12. In RBAC - the link to the file uploaded is broken. Something in the file structure is broken and you get for:
>     `contentToUpload = open(os.path.expanduser('~')+'/'+fileName, 'rb') # Only a single file per upload which must be named \\\"content\\\"`
>     `An error that Errno 2] No such file or directory: '/home/jovyan/lakefs_test.csv`
>     So I didn’t continue testing after this.

✅ Fixed

> 13. Regrading reprocess backfill - IMHO since this somewhat of a hack, I would include it, but not reference it from the menu (00_index) - but it does work.

I'm going to include it because the index should be comprehensive, but I'll add a note to the notebook that it's a hack. Is there a better option to direct people to? 

> 14. For airflow, I think we should have an example that is prebuilt and includes the 3 airflow examples that are a part of multiple samples today. No? I couldn’t find those in the new release and we use them a lot.

There are still the three here: https://github.com/treeverse/lakeFS-samples/tree/new-eb/03-multiple-samples -- are those the ones you mean? 
There is also the example here https://github.com/treeverse/lakeFS-samples/tree/new-eb/standalone/airflow-dag-example

Subsequent stages of this work could be consolidating the samples so that we just have a single canonical reference if that would be useful. 

> 15. When I tried simply docker compose up I got:
> 
> ```
>  => [internal] load build definition from Dockerfile                                                                               0.0s
>  => => transferring dockerfile: 2B                                                                                                 0.0s
> failed to solve: rpc error: code = Unknown desc = failed to solve with frontend dockerfile.v0: failed to read dockerfile: open /var/lib/docker/tmp/buildkit-mount235955284/Dockerfile: no such file or directory```
> ```

Ah yes, this was my mistake. Can you run this from the repo root folder and then try again: 

```
git submodule init
git submodule update
```

I've updated the README to include this too.

**Comment by iddoavn** [comment]
I was able to run the docker compose up now however:

1. There is no place to insert the email for the server. Especially if we believe that this can be the first step of the process, that is critical to do.
2. `Version Control of multi-buckets pipelines` will not work with the OOTB credentials since it creates links that will not work:
brokenLink
3. Minor suggestion, I would write:
* **lakeFS** can be provisioned as part of this environment, or provided by [lakeFS cloud](http://https://lakefs.cloud/) or [your own installation](https://docs.lakefs.io/quickstart/) 

Since we WANT (I think) the user to go through this journey.
4. Regarding the pre-populated variables. What I want to prevent is someone using this against a lakeFS server and thinking they shouldn't have. Maybe we can instead add those in the comments?

5. I sense I'm not communicating well why I think some of this will drive lakeFS cloud users to a local installation. I wish to make sure if you provision a lakeFS Cloud instance, it doesn't feel like you are not following a "standard" way. That's why I keep going back to the wording. I suggest this as the wording below instead of the section from "You have two options" until the environment details. Are you comfortable with that wording?


You now have two options: 

### **Run a small footprint container, including only the notebook against your lakeFS Server** 

If you have already [spun up a lakeFS server](https://docs.lakefs.io/quickstart/) or utilizing [lakeFS cloud](http://https://lakefs.cloud/), all you need to run is the Jupyter notebook server: 

```bash
docker compose up jupyter-notebook
```

Once the stack's up and running, open the Jupyter Notebook (http://localhost:8888) and check out the [catalog of sample notebooks](./notebooks/00_index.ipynb) to explore lakeFS. 

You can then configure these notebook to work against your own object storage.

### **Don't have a lakeFS Server or access to an object store?**

If you want to provision a lakeFS server, a MinIO Object store as well as Jupyter, then bring up the full stack:

```bash
# make sure we've got the lakeFS hooks content too
git submodule init
git submodule update

docker compose up
```

As above, open the Jupyter Notebook (http://localhost:8888) peruse the [catalog of sample notebooks](./notebooks/00_index.ipynb) to explore lakeFS. 

6. If a local lakeFS instance can't be run side by side with the sample, then that's an issue IMHO. Is that because of the networking between the docker images?

7. For the Notebooks for Demos and Conference Talks - I think the "multi table transaction" link is broken. The Dog example also doesn't seem exactly Kosher. Should we remove this secion altogether? (especially since the use cases are presented elsewhere)

8. IMHO for the same reason we can remove "O'Reilly CI/CD for Data Lakes - lakeFS Course Challenge!"

9. What I meant by airflow is that I think the link to the stand alone airflow and lakeFS examples ( https://github.com/treeverse/lakeFS-samples/blob/main/standalone/airflow-dag-example ) should actually be to a directory that looks like 03 but only had these 3 notebooks (similar to how the Dagster link is working) - because these are the best airflow examples we have IMHO. 

10. Regarding the backfill - I wouldn't add a note it is a hack :) Perhaps just remove it and we can use it internally if we needed to?

**Review by iddoavn — APPROVED** [review]
Follow our discussion:
1. let's make sure to follow up on the comments below after the merge (so we dont get blocked now).
2. We should keep track of the number of installations with and without emails because that will both let us know if we need to urgently add email collection here AND if there is actual usage of the notebook.

**Comment by rmoff** [comment]
Followup tasks post-merge:

- [ ] https://github.com/treeverse/devex-internal/issues/270
- [ ] https://github.com/treeverse/devex-internal/issues/274
  - [ ] https://github.com/treeverse/lakeFS/issues/6033
- [ ] https://github.com/treeverse/lakeFS-samples/issues/77

**Pull request merged**
