### PR TITLE
Enable samples to be run by the user in parallel

### PR DESCRIPTION
**Pull request by rmoff**
Allocate unique ports and container names so that samples can be run in parallel

For background see https://github.com/treeverse/devex-internal/issues/284

### CODE REVIEW

**Comment by rmoff** [comment]
@iddoavn @kesarwam LMK if you want this change made, or if I should close the PR off without merging. Thanks.

**Comment by kesarwam** [comment]
Please test whenever you make any changes. I am getting following error to run Dagster demo because minio container already exists in lakefs-samples container group:

`ak@Amits-MacBook-Pro dagster-integration %    docker compose up                                        
[+] Running 1/0
 ⠿ Network dagster-integration_default             Created                                                                                                                                0.0s
 ⠋ Container dagster-integration-jupyter-notebook  Creating                                                                                                                               0.0s
 ⠋ Container minio                                 Creating                                                                                                                               0.0s
Error response from daemon: Conflict. The container name "/minio" is already in use by container "4d86b2abecf18680035461b10956942abe6f4bf76cd9552bd004b9dce5deee8b". You have to remove (or rename) that container to be able to reuse that name.
`

**Comment by kesarwam** [comment]
Also, Dagster notebooks use port # for the UI. This should also be changed:
image

**Comment by kesarwam** [comment]
You changed Dagster demo from Docker run to Docker Compose and you included lakefs and minio in Docker Compose file. Now we will have conflicts of port # for lakefs and minio containers if I am running both lakefs-samples and Dagster demos concurrently.

image

**Comment by rmoff** [comment]
> Please test whenever you make any changes. 

😄  

> I am getting following error to run Dagster demo because minio container already exists in lakefs-samples container group:
> 
> ak@Amits-MacBook-Pro dagster-integration % docker compose up [+] Running 1/0 ⠿ Network dagster-integration_default Created 0.0s ⠋ Container dagster-integration-jupyter-notebook Creating 0.0s ⠋ Container minio Creating 0.0s Error response from daemon: Conflict. The container name "/minio" is already in use by container "4d86b2abecf18680035461b10956942abe6f4bf76cd9552bd004b9dce5deee8b". You have to remove (or rename) that container to be able to reuse that name.

The fix @ozkatz and I just made should fix this, as it'll prefix each container with the name of its Docker Compose. 

> Also, Dagster notebooks use port # for the UI. This should also be changed: image

Fixed

> Now we will have conflicts of port # for lakefs and minio containers if I am running both lakefs-samples and Dagster demos concurrently.

From the conversations with @iddoavn I thought you guys just rant the notebook? lakeFS-samples and Dagster use different ports for the notebook so there is no port conflict. Just use `docker compose up jupyter-notebook` on the respective demo.

**Comment by rmoff** [comment]
> I am getting port conflict issue because I am already running lakefs-samples which includes minio.

From the conversations with @iddoavn I thought you guys just ran the notebook? lakeFS-samples and Dagster use different ports for the notebook so there is no port conflict. Just use `docker compose up jupyter-notebook` on the respective demo.

**Comment by iddoavn** [comment]
Even if we run` docker compose up jupyter-notebook` , I don't think we should expect everyone to run it that way (especially since the default will be without, and that if you stop and start from the docker UI, it will run docker compose up anyway. 
So why not have the MinIO also on different ports here?

**Comment by rmoff** [comment]
I've updated MinIO in the dagster example to be on a different port, and run both notebooks through successfully to test. 

@kesarwam @iddoavn please review and +1 so I can get this PR merged. thanks :)

**Comment by kesarwam** [comment]
@rmoff I added correct port number for local lakeFS instance in lakefs_resources.py for Dagster demo otherwise URL output from Dagster job doesn't work.

**Review by kesarwam — APPROVED** [review]

**Pull request merged**
